[package]
name = "day1"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "d1p1"
path = "src/day1/part1.rs"

[[bin]]
name = "d1p2"
path = "src/day1/part2.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
